management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "*"
#      base-path: "/manage"
  endpoint:
    health:
#      show-details: always # detail health info
      show-components: always # simple health info
  info:
    java:
      enabled: true
    os:
      enabled: true

logging:
  level:
    hello.controller: debug

server:
  tomcat:
    mbeanregistry:
      enabled: true
